/** 
* Note:  This file is was generated by the GTRI IDL Compiler.
* This file should not be edited directly, if errors are found,
* please contact the individual listed below.
* 
* Developer:  Marcus Quettan
* Email: marcus.quettan@gtri.gatech.edu
*
**/

#ifndef FACE_DM_UOPMODELNAME_PV1_H
#define FACE_DM_UOPMODELNAME_PV1_H
#include <FACE/types.h>
#include <FACE/interface.h>
#include <FACE/sequence.h>
#include <FACE/string.h>
#include <FACE/fixed.h>
#include <FACE/DM/UoPModelName/T1.h>
#include <FACE/DM/UoPModelName/T2.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Struct FACE_DM_UoPModelName_PV1 Begin */
typedef struct FACE_DM_UoPModelName_PV1 {
  FACE_DM_UoPModelName_T1 t1;
  FACE_DM_UoPModelName_T2 t2;
} FACE_DM_UoPModelName_PV1;

static inline FACE_interface_return FACE_DM_UoPModelName_PV1_init(FACE_DM_UoPModelName_PV1 *instance)
{
  return FACE_INTERFACE_NO_ERROR;
}
/* Struct FACE_DM_UoPModelName_PV1 End */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif // FACE_DM_UOPMODELNAME_PV1_H
