#include "FACE/Common.idl"
//! Source file: FACE/DM/UoPModelName/T2.idl

#ifndef FACE_DM_UOPMODELNAME_T2
#define FACE_DM_UOPMODELNAME_T2

#include <FACE/DM/DataModelName/idlEnum1.idl>
#include <FACE/DM/DataModelName/M2.idl>

module FACE
{
    module DM
    {
        module UoPModelName
        {
            module T_T2
            {
                typedef sequence<FACE::DM::DataModelName::idlEnum1> Seq_idlEnum1;
                
                struct T2
                {
                    FACE::DM::DataModelName::M2 mypobs3;
                    Seq_idlEnum1 pobs6;
                };
            };
            typedef T_T2::T2 T2;
        };
    };
};

#endif // FACE_DM_UOPMODELNAME_T2
