//! Source file: FACE/DM/DataModelName/idlFloat1.idl

#ifndef FACE_DM_DATAMODELNAME_IDLFLOAT1
#define FACE_DM_DATAMODELNAME_IDLFLOAT1

module FACE
{
    module DM
    {
        module DataModelName
        {
            typedef float idlFloat1;
        };
    };
};

#endif // FACE_DM_DATAMODELNAME_IDLFLOAT1
