//! Source file: FACE/DM/DataModelName/idlLongDouble1.idl

#ifndef FACE_DM_DATAMODELNAME_IDLLONGDOUBLE1
#define FACE_DM_DATAMODELNAME_IDLLONGDOUBLE1

module FACE
{
    module DM
    {
        module DataModelName
        {
            typedef long double idlLongDouble1;
        };
    };
};

#endif // FACE_DM_DATAMODELNAME_IDLLONGDOUBLE1
