//! Source file: FACE/DM/DataModelName/M1.idl

#ifndef FACE_DM_DATAMODELNAME_M1
#define FACE_DM_DATAMODELNAME_M1

#include <FACE/DM/DataModelName/idlDouble1.idl>
#include <FACE/DM/DataModelName/M1A3.idl>

module FACE
{
    module DM
    {
        module DataModelName
        {
            struct M1
            {
                idlDouble1 m1a2;
                M1A3 m1a3;
            };
        };
    };
};

#endif // FACE_DM_DATAMODELNAME_M1
