//! Source file: FACE/DM/DataModelName/M1A3.idl

#ifndef FACE_DM_DATAMODELNAME_M1A3
#define FACE_DM_DATAMODELNAME_M1A3

#include <FACE/DM/DataModelName/idlFixed1.idl>
#include <FACE/DM/DataModelName/idlLongDouble1.idl>

module FACE
{
    module DM
    {
        module DataModelName
        {
            struct M1A3
            {
                idlFixed1 fixedb;
                idlLongDouble1 longDouble;
            };
        };
    };
};

#endif // FACE_DM_DATAMODELNAME_M1A3
