/** 
* Note:  This file is was generated by the GTRI IDL Compiler.
* This file should not be edited directly, if errors are found,
* please contact the individual listed below.
* 
* Developer:  Marcus Quettan
* Email: marcus.quettan@gtri.gatech.edu
*
**/

#ifndef FACE_DM_DATAMODELNAME_IDLDOUBLE1_H
#define FACE_DM_DATAMODELNAME_IDLDOUBLE1_H
#include <FACE/types.h>
#include <FACE/interface.h>
#include <FACE/sequence.h>
#include <FACE/string.h>
#include <FACE/fixed.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

typedef FACE_double FACE_DM_DataModelName_idlDouble1;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif // FACE_DM_DATAMODELNAME_IDLDOUBLE1_H
