/** 
* Note:  This file is was generated by the GTRI IDL Compiler.
* This file should not be edited directly, if errors are found,
* please contact the individual listed below.
* 
* Developer:  Marcus Quettan
* Email: marcus.quettan@gtri.gatech.edu
*
**/

#ifndef FACE_DM_DATAMODELNAME_M1A3_H
#define FACE_DM_DATAMODELNAME_M1A3_H
#include <FACE/types.h>
#include <FACE/interface.h>
#include <FACE/sequence.h>
#include <FACE/string.h>
#include <FACE/fixed.h>
#include <FACE/DM/DataModelName/idlFixed1.h>
#include <FACE/DM/DataModelName/idlLongDouble1.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Struct FACE_DM_DataModelName_M1A3 Begin */
typedef struct FACE_DM_DataModelName_M1A3 {
  FACE_DM_DataModelName_idlFixed1 fixedb;
  FACE_DM_DataModelName_idlLongDouble1 longDouble;
} FACE_DM_DataModelName_M1A3;

static inline FACE_interface_return FACE_DM_DataModelName_M1A3_init(FACE_DM_DataModelName_M1A3 *instance)
{
  if (FACE_FIXED_NO_ERROR != 
      FACE_fixed_init(&(instance->fixedb), 
          FACE_DM_DataModelName_idlFixed1_digits,
          FACE_DM_DataModelName_idlFixed1_scale)){
    return FACE_INTERFACE_LOGIC_ERROR;
  }
  return FACE_INTERFACE_NO_ERROR;
}
/* Struct FACE_DM_DataModelName_M1A3 End */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif // FACE_DM_DATAMODELNAME_M1A3_H
