with FACE;
with IDL_Modules;
use IDL_Modules;
with IDL_Modules.FACE_IDL_3_1_TSS_1_1_CSP_1_1;
package FACE.TSS.CSP is
	
	subtype DATA_STORE_KIND_TYPE is IDL_Modules.FACE_IDL_3_1_TSS_1_1_CSP_1_1.DATA_STORE_KIND_TYPE;
	function PRIVATE_DATA_STORE return IDL_Modules.FACE_IDL_3_1_TSS_1_1_CSP_1_1.DATA_STORE_KIND_TYPE renames IDL_Modules.FACE_IDL_3_1_TSS_1_1_CSP_1_1.PRIVATE_DATA_STORE;
	function CHECKPOINT_DATA_STORE return IDL_Modules.FACE_IDL_3_1_TSS_1_1_CSP_1_1.DATA_STORE_KIND_TYPE renames IDL_Modules.FACE_IDL_3_1_TSS_1_1_CSP_1_1.CHECKPOINT_DATA_STORE;
	
	subtype DATA_STORE_TOKEN_TYPE is IDL_Modules.FACE_IDL_3_1_TSS_1_1_CSP_1_1.DATA_STORE_TOKEN_TYPE;
	
	subtype DATA_ID_TYPE is IDL_Modules.FACE_IDL_3_1_TSS_1_1_CSP_1_1.DATA_ID_TYPE;
	

end FACE.TSS.CSP;